### ISSUE TITLE
Additional document request: thread saftey

### ISSUE THREAD

**Issue by samrueby** [RobThree/TwoFactorAuth.Net#13]
I'm wondering if the methods provided by `TwoFactorAuth` are thread safe. If they are, it would make the most sense in apps to create a single long-lived instance of `TwoFactorAuth`. To use throughout your app.

**Comment by RobThree** [comment]
Well, yes and no. Technically: no. It can't be guaranteed because any of the used `IQrCodeProvider`, `IRngProvider` and `ITimeProvider` that the `TwoFactorAuthNet` uses can be non-thread-safe. If you stick to the built-in ones or other implementations that declare to be thread-safe you _should_ be fine. The `TwoFactorAuthNet` class itself has some properties that can only be set during construction and are read-only after that and, AFAIK and also what a cursory glance over the class showed it _should_ be thread-safe. Not guaranteeing it 100% but I don't see why it wouldn't be.
